# xrd-vcluster.yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositevclusters.vcluster.crossplane.io
spec:
  group: vcluster.crossplane.io
  names:
    kind: CompositeVCluster
    plural: compositevclusters
  claimNames:
    kind: VCluster
    plural: vclusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clusterName:
                  type: string
