# composition-pr-environment.yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: pr-environment
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XPREnvironment
  resources:
  - name: vcluster
    base:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release
      metadata:
        name: vcluster-pr
      spec:
        providerConfigRef:
          name: default-helm
        forProvider:
          chart:
            name: vcluster
            repo: https://charts.loft.sh
            version: "0.15.0" # Example version
          namespace: vclusters
          values: |
            syncer:
              extraArgs:
                - "--fake-kubelets"
    patches:
    - fromFieldPath: "spec.parameters.name"
      toFieldPath: "metadata.name"
    - fromFieldPath: "spec.parameters.chartVersion"
      toFieldPath: "spec.forProvider.chart.version"
