apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vcluster-composition
spec:
  compositeTypeRef:
    apiVersion: vcluster.crossplane.io/v1alpha1
    kind: CompositeVCluster
  resources:
    - name: vcluster
      base:
        apiVersion: vcluster.loft.sh/v1
        kind: VCluster
        metadata:
          name: vcluster-default
          namespace: vcluster-default
        spec:
          replicas: 1
          chart:
            repo: https://charts.loft.sh
            name: vcluster
            version: "0.15.2"
          storage:
            size: 2Gi
          service:
            type: LoadBalancer
      patches:
        - fromFieldPath: "spec.clusterName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.clusterName"
          toFieldPath: "metadata.namespace"
