# xrd-pr-environment.yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xprenvironments.example.org
spec:
  group: example.org
  names:
    kind: XPREnvironment
    plural: xprenvironments
    singular: xprenvironment
  claimNames:
    kind: PREnvironment
    plural: prenvironments
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # Define 'parameters' here, as the Composition uses spec.parameters.name and spec.parameters.chartVersion
                parameters:
                  type: object
                  properties:
                    name:
                      type: string
                    chartVersion:
                      type: string
