# argocd-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pr-environments
  namespace: argocd
spec:
  project: pr-environments
  source:
    repoURL: 'https://github.com/maskaravivek/echo-server-k8s-argocd-crossplane.git'
    targetRevision: main
    path: 'environments/pr'
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
