# This is an example ArgoCD App that uses the Helm provider
# to deploy a virtual cluster.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster
  namespace: argocd
spec:
  project: default
  source:
    chart: vcluster
    repoURL: https://charts.loft.sh
    helm:
      releaseName: vcluster
      valueFiles:
        - vcluster.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: my-namespace