name: PR Environment Management

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main

env:
  REPO_NAME: ${{ github.event.repository.name }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PR_LINK: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push-app:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.revision=${{ github.event.pull_request.head.sha }}
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.vendor=loft.sh
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.description=Simple echo app based on the HashiCorp echo-http.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${{ github.event.pull_request.head.sha }} | cut -c1-8`" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src
          platforms: linux/amd64
          push: true
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
          labels: ${{ steps.meta.outputs.labels }}
  manage-environment:
    needs: build-push-app
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Authenticate to Kubernetes cluster
        run: |
          aws eks --region us-west-2 update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main

      - name: Login to vCluster Platform instance
        env:
          LOFT_URL: ${{ secrets.LOFT_URL }}
          ACCESS_KEY: ${{ secrets.VCLUSTER_PLATFORM_ACCESS_KEY }}
        run: vcluster login $LOFT_URL --access-key $ACCESS_KEY

      - name: Create Virtual Cluster for PR
        uses: loft-sh/create-vcluster@main
        with:
          name: pr-${{ github.sha }}

      # - name: Set up Kubernetes tools
      #   run: |
      #     curl -sLO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      #     chmod +x kubectl
      #     sudo mv kubectl /usr/local/bin/
      #     curl -sLO https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz
      #     tar -zxvf helm-v3.9.0-linux-amd64.tar.gz
      #     sudo mv linux-amd64/helm /usr/local/bin/
      #     curl -Lo vcluster-bin https://github.com/loft-sh/vcluster/releases/latest/download/vcluster-linux-amd64
      #     chmod +x vcluster-bin
      #     sudo mv vcluster-bin /usr/local/bin/vcluster

      # - name: Authenticate to vcluster platform
      #   # Use your own credentials or secrets; this is just an example
      #   run: |
      #     vcluster platform login https://samplecrossplaceargocdgithubpr.vcluster.cloud/ --access-key ${{ secrets.VCLUSTER_PLATFORM_ACCESS_KEY }}

      # - name: Install vCluster CLI
      #   uses: loft-sh/setup-vcluster@main
      # - name: Install vCluster CLI
      #   uses: loft-sh/setup-loft@v2
      #   with:
      #     version: v3.0.0
      #     url: https://fiq5rbu.loft.host
      #     # Specify your vCluster Platform access key here
      #     access-key: ${{ secrets.VCLUSTER_PLATFORM_ACCESS_KEY }}
      #     # Optional if your vCluster Platform domain certificate is insecure
      #     #insecure: true

      # - name: Create PR preview environment
      #   uses: loft-sh/create-vcluster@main
      #   with:
      #     name: ${REPO_NAME}-pr-${PR_NUMBER}
      #     template: preview-template
      #     project: default

      # - name: Create PR preview environment
      #   run: |
      #     # This creates a vcluster-based ephemeral environment tied to the PR
          
      #     INGRESS_HOST=loft-preview-${{ github.event.pull_request.number }}-fiq5rbu.loft.host

      #     helm repo add argo https://argoproj.github.io/argo-helm
      #     helm install argocd argo/argo-cd --version 5.16.3 \
      #         --create-namespace \
      #         -n argocd \
      #         --set server.ingress.enabled=true \
      #         --set server.ingress.hosts={$INGRESS_HOST}

      # - name: Create PR preview environment
      #   run: |
      #     # This creates a vcluster-based ephemeral environment tied to the PR
          
      #     INGRESS_HOST=loft-preview-${{ github.event.pull_request.number }}-fiq5rbu.loft.host

      #     vcluster create ${REPO_NAME}-pr-${PR_NUMBER} --project default --recreate --template preview-template --connect --expose

      #     helm repo add argo https://argoproj.github.io/argo-helm
      #     helm install argocd argo/argo-cd --version 5.16.3 \
      #         --create-namespace \
      #         -n argocd \
      #         --set server.ingress.enabled=true \
      #         --set server.ingress.hosts={$INGRESS_HOST}

      # - name: Create or Delete vCluster
      #   env:
      #     PR_NUMBER: ${{ github.event.number }}
      #   run: |
      #     if [ "${{ github.event.action }}" != "closed" ]; then
      #       # Create namespace for the vCluster
      #       kubectl create namespace vcluster-pr-${PR_NUMBER}

      #       # Render the vCluster YAML template and apply it
      #       sed "s/{{PR_NUMBER}}/${PR_NUMBER}/g" vcluster/vcluster-template.yaml | kubectl apply -f -
      #     else
      #       # Delete the VCluster resource
      #       kubectl delete vcluster vcluster-pr-${PR_NUMBER} -n vcluster-pr-${PR_NUMBER} --ignore-not-found
      #       # Delete the namespace
      #       kubectl delete namespace vcluster-pr-${PR_NUMBER} --ignore-not-found
      #     fi

      # - name: Wait for vCluster to be ready
      #   if: ${{ github.event.action != 'closed' }}
      #   env:
      #     PR_NUMBER: ${{ github.event.number }}
      #   run: |
      #     # Check if vCluster resource exists
      #     kubectl get vcluster vcluster-pr-${PR_NUMBER} -n vcluster-pr-${PR_NUMBER} --no-headers || {
      #       echo "vCluster resource not found. Exiting.";
      #       exit 1;
      #     }

      #     # Wait until the vCluster is ready
      #     kubectl wait --for=condition=Ready vcluster/vcluster-pr-${PR_NUMBER} -n vcluster-pr-${PR_NUMBER} --timeout=900s

      # - name: Debug vCluster Creation
      #   if: ${{ failure() && github.event.action != 'closed' }}
      #   env:
      #     PR_NUMBER: ${{ github.event.number }}
      #   run: |
      #     kubectl describe vcluster vcluster-pr-${PR_NUMBER} -n vcluster-pr-${PR_NUMBER}
      #     kubectl get events -n vcluster-pr-${PR_NUMBER} --sort-by='.metadata.creationTimestamp'

      # - name: Debug vCluster Pods
      #   if: ${{ failure() && github.event.action != 'closed' }}
      #   env:
      #     PR_NUMBER: ${{ github.event.number }}
      #   run: |
      #     kubectl get pods -n vcluster-pr-${PR_NUMBER} -o wide
      #     kubectl describe pods -n vcluster-pr-${PR_NUMBER}

      # - name: Fetch vCluster Logs
      #   if: ${{ failure() && github.event.action != 'closed' }}
      #   env:
      #     PR_NUMBER: ${{ github.event.number }}
      #   run: |
      #     kubectl logs -n vcluster-pr-${PR_NUMBER} -l app.kubernetes.io/name=vcluster

      # - name: Register vCluster with Argo CD
      #   if: ${{ github.event.action != 'closed' }}
      #   env:
      #     PR_NUMBER: ${{ github.event.number }}
      #   run: |
      #     argocd login ${{ secrets.ARGOCD_SERVER }} --insecure --username admin --password ${{ secrets.ARGOCD_PASSWORD }}
      #     argocd cluster add --name vcluster-pr-${PR_NUMBER} --kubeconfig ./vcluster-pr-${PR_NUMBER}-kubeconfig --insecure

      # - name: Create Argo CD Application
      #   if: ${{ github.event.action != 'closed' }}
      #   env:
      #     PR_NUMBER: ${{ github.event.number }}
      #   run: |
      #     sed "s/{{PR_NUMBER}}/${PR_NUMBER}/g" argocd/argocd-application-template.yaml | kub
